[theme]
primaryColor = "#f97316"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
